conky.config = {
    alignment = "bottom_middle",
    own_window = true,
    own_window_type = "dock",
    own_window_transparent = true,
    double_buffer = true,
    update_interval = 1,
    use_xft = true,
    font = "DejaVu Sans:size=28",
    minimum_width = 30,
    minimum_height = 60,
    gap_y = 30,
};

conky.text = [[
${alignc}${execpi 1 echo $(( $(date +%s) - $(cat ~/.config/conky/.stopwatch_start 2>/dev/null || date +%s) )) | awk '{printf "%02d:%02d:%02d", $1/3600, ($1%3600)/60, $1%60}'}
]];
